name: Go Tests

on: [push, pull_request]

jobs:
  test:
    name: Test Library
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.0'  # Use the version of Go your project requires

      - name: Check out code
        uses: actions/checkout@v3

      - name: Tidy Go Modules
        run: go mod tidy

      - name: Download Go Modules
        run: go mod download

      - name: Run Tests
        run: go test ./...